### ISSUE TITLE
How to get username and password

### ISSUE THREAD

**Issue by TopPython** [smartcatai/SmartCAT-API#9]
I think we use username as account ID and password as apikey
But I cannot login with my account ID and apikey
Please let me know how to login to smartcat api

**Comment by AndreySavenkov** [comment]
This can be caused, because of your account is not on Smartcat EU-server (it is used by default in constructor).
Server address is the 3-rd optional parameter in constructor.
Try adding it based on your Smartcat server region like on screenshot

<img width="1175" alt="Снимок экрана 2021-01-11 в 09 12 27" src="https://user-images.githubusercontent.com/497800/104151202-70d08380-53ed-11eb-9532-0616390feab4.png">
